import 'package:flutter/material.dart';

var kprimaryColor = Color.fromARGB(255, 3, 34, 58);
var backgroundColor = Color.fromARGB(255, 237, 221, 75);
List allah_name = [
  'ٱلْرَّحْمَـانُ',
  'ٱلْرَّحِيْمُ',
  'ٱلْمَلِكُ',
  'ٱلْقُدُّوسُ',
  'ٱلْسَّلَامُ',
  'ٱلْمُؤْمِنُ',
  'ٱلْمُهَيْمِنُ',
  'ٱلْعَزِيزُ',
  'ٱلْجَبَّارُ',
  'ٱلْمُتَكَبِّرُ',
  'ٱلْخَالِقُ',
  'ٱلْبَارِئُ',
  'ٱلْمُصَوِّرُ',
  'ٱلْغَفَّارُ',
  'ٱلْقَهَّارُ',
  'ٱلْوَهَّابُ',
  'ٱلْرَّزَّاقُ',
  'ٱلْفَتَّاحُ',
  'ٱلْعَلِيمُ',
  'ٱلْقَابِضُ',
  'ٱلْبَاسِطُ',
  'ٱلْخَافِضُ',
  'ٱلْرَّافِعُ',
  'ٱلْمُعِزُّ',
  'ٱلْمُذِلُّ',
  'ٱلْسَّمِيعُ',
  'ٱلْبَصِيرُ',
  'ٱلْبَصِيرُ',
  'ٱلْعَدْلُ',
  'ٱلْعَدْلُ',
  'ٱلْخَبِيرُ',
  'ٱلْحَلِيمُ',
  'ٱلْعَظِيمُ',
  'ٱلْغَفُورُ',
  'ٱلْشَّكُورُ',
  'ٱلْعَلِيُّ',
  'ٱلْكَبِيرُ',
  'ٱلْحَفِيظُ',
  'ٱلْمُقِيتُ',
  'ٱلْحَسِيبُ',
  'ٱلْجَلِيلُ',
  'ٱلْكَرِيمُ',
  'ٱلْرَّقِيبُ',
  'ٱلْمُجِيبُ',
  'ٱلْوَاسِعُ',
  'ٱلْحَكِيمُ',
  'ٱلْوَدُودُ',
  'ٱلْمَجِيدُ',
  'ٱلْبَاعِثُ',
  'ٱلْشَّهِيدُ',
  'ٱلْحَقُّ',
  'ٱلْوَكِيلُ',
  'ٱلْقَوِيُّ',
  'ٱلْمَتِينُ',
  'ٱلْوَلِيُّ',
  'ٱلْحَمِيدُ',
  'ٱلْمُحْصِيُ',
  'ٱلْمُبْدِئُ',
  'ٱلْمُعِيدُ',
  'ٱلْمُحْيِى',
  'ٱلْمُمِيتُ',
  'ٱلْحَىُّ',
  'ٱلْقَيُّومُ',
  'ٱلْوَاجِدُ',
  'ٱلْمَاجِدُ',
  'ٱلْوَاحِدُ',
  'ٱلْأَحَد',
  'ٱلْصَّمَدُ',
  'ٱلْقَادِرُ',
  'ٱلْمُقْتَدِرُ',
  'ٱلْمُقَدِّمُ',
  'ٱلْمُؤَخِّرُ',
  'ٱلأَوَّلُ',
  'ٱلْآخِرُ',
  'ٱلْظَّاهِرُ',
  'ٱلْبَاطِنُ',
  'ٱلْوَالِي',
  'ٱلْمُتَعَالِي',
  'ٱلْبَرُّ',
  'ٱلْتَّوَّابُ',
  'ٱلْمُنْتَقِمُ',
  'ٱلْعَفُوُّ',
  'ٱلْرَّؤُفُ',
  'مَالِكُ ٱلْمُلْكُ',
  'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ',
  'ٱلْمُقْسِطُ',
  'ٱلْجَامِعُ',
  'ٱلْغَنيُّ',
  'ٱلْمُغْنِيُّ',
  'ٱلْمَانِعُ',
  'ٱلْضَّارُ',
  'ٱلْنَّافِعُ',
  'ٱلْنُّورُ',
  'ٱلْهَادِي',
  'ٱلْبَدِيعُ',
  'ٱلْبَاقِي',
  'ٱلْوَارِثُ',
  'ٱلْرَّشِيدُ',
  'ٱلْصَّبُورُ',
];

List allah_name_mean = [
  'The Most or Entirely Merciful',
  'The Bestower of Mercy',
  'The King and Owner of Dominion',
  'The Absolutely Pure',
  'The Perfection and Giver of Peace',
  'The One Who gives Emaan and Security',
  'The Guardian, The Witness, The Overseer',
  'The All Mighty',
  'The Compeller, The Restorer',
  'The Supreme, The Majestic',
  'The Creator, The Maker',
  'The Originator',
  'The Fashioner',
  'The All- and Oft-Forgiving',
  'The Subduer, The Ever-Dominating',
  'The Giver of Gifts',
  'The Provider',
  'The Opener, The Judge',
  'The All-Knowing, The Omniscient',
  'The Withholder',
  'The Extender',
  'The Reducer, The Abaser',
  'The Exalter, The Elevator',
  'The Honourer, The Bestower',
  'The Dishonourer, The Humiliator',
  'The All-Hearing',
  'The All-Seeing',
  'The Judge, The Giver of Justice',
  'The Utterly Just',
  'The Subtle One, The Most Gentle',
  'The Acquainted, the All-Aware',
  'The Most Forbearing',
  'The Most Forbearing',
  'The Most Forbearing',
  'The Most Appreciative',
  'The Most High, The Exalted',
  'The Most High, The Exalted',
  'The Preserver, The All-Heedful and All-Protecting',
  'The Sustainer',
  'The Reckoner, The Sufficient',
  'The Majestic',
  'The Most Generous, The Most Esteemed',
  'The Watchful',
  'The Responsive One',
  'The All-Encompassing, the Boundless',
  'The All-Wise',
  'The Most Loving',
  'The Most Loving',
  'The Most Loving',
  'The All- and Ever Witnessing',
  'The Absolute Truth',
  'The Trustee, The Disposer of Affairs',
  'The All-Strong',
  'The Firm, The Steadfast',
  'The Protecting Associate',
  'The Praiseworthy',
  'The All-Enumerating, The Counter',
  'The Originator, The Initiator',
  'The Restorer, The Reinstater',
  'The Giver of Life',
  'The Bringer of Death, the Destroyer',
  'The Ever-Living',
  'The Sustainer, The Self-Subsisting',
  'The Perceiver',
  'The Illustrious, the Magnificent',
  'The One',
  'The Unique, The Only One',
  'The Eternal, Satisfier of Needs',
  'The Capable, The Powerful',
  'The Omnipotent',
  'The Expediter, The Promoter',
  'The Delayer, the Retarder',
  'The First',
  '	The Last',
  'The Manifest',
  'The Hidden One, Knower of the Hidden',
  'The Governor, The Patron',
  'The Self Exalted',
  'The Source of Goodness, the Kind Benefactor',
  'The Ever-Pardoning, The Relenting',
  'The Avenger',
  'The Pardoner',
  'The Most Kind',
  'Master of the Kingdom, Owner of the Dominion',
  'Possessor of Glory and Honour, Lord of Majesty and Generosity',
  'The Equitable, the Requiter',
  'The Gatherer, the Uniter',
  'The Self-Sufficient, The Wealthy',
  'The Enricher',
  'The Withholder',
  'The Distresser',
  'The Propitious, the Benefactor',
  'The Light, The Illuminator',
  'The Guide',
  'The Incomparable Originator',
  'The Ever-Surviving, The Everlasting',
  'The Inheritor, The Heir',
  'The Guide, Infallible Teacher',
  'The Forbearing, The Patient',
];

List hadith_bhukari = [
  'ہمیں محمد بن مثنیٰ نے یہ حدیث بیان کی، ان کو عبدالوہاب ثقفی نے، ان کو ایوب نے، وہ ابوقلابہ سے روایت کرتے ہیں، وہ انس رضی اللہ عنہ سے ناقل ہیں   وہ نبی کریم صلی اللہ علیہ وسلم سے آپ صلی اللہ علیہ وسلم نے فرمایا تین خصلتیں ایسی ہیں کہ جس میں یہ پیدا ہو جائیں اس نے ایمان کی مٹھاس کو پا لیا۔ اول یہ کہ اللہ اور اس کا رسول اس کے نزدیک سب سے زیادہ محبوب بن جائیں، دوسرے یہ کہ وہ کسی انسان سے محض اللہ کی رضا کے لیے محبت رکھے۔ تیسرے یہ کہ وہ کفر میں واپس لوٹنے کو ایسا برا جانے جیسا کہ آگ میں ڈالے جانے کو برا جانتا ہے۔ ',
  'ہم سے اس حدیث کو ابوالولید نے بیان کیا، ان سے شعبہ نے، انہیں عبداللہ بن جبیر نے خبر دی، وہ کہتے ہیں کہ ہم نے انس بن مالک رضی اللہ عنہ سے اس کو سنا، وہ رسول اللہ صلی اللہ علیہ وسلم سے روایت کرتے ہیں کہ   آپ صلی اللہ علیہ وسلم نے فرمایا انصار سے محبت رکھنا ایمان کی نشانی ہے اور انصار سے کینہ رکھنا نفاق کی نشانی ہے۔ ',
  'ہم سے اس حدیث کو ابوالیمان نے بیان کیا، ان کو شعیب نے خبر دی، وہ زہری سے نقل کرتے ہیں، انہیں ابوادریس عائذ اللہ بن عبداللہ نے خبر دی کہ   عبادہ بن صامت رضی اللہ عنہ جو بدر کی لڑائی میں شریک تھے اور لیلۃالعقبہ کے ( بارہ ) نقیبوں میں سے تھے۔ فرماتے ہیں کہ رسول اللہ صلی اللہ علیہ وسلم نے اس وقت جب آپ کے گرد صحابہ کی ایک جماعت بیٹھی ہوئی تھی فرمایا کہ مجھ سے بیعت کرو اس بات پر کہ اللہ کے ساتھ کسی کو شریک نہ کرو گے، چوری نہ کرو گے، زنا نہ کرو گے، اپنی اولاد کو قتل نہ کرو گے اور نہ عمداً کسی پر کوئی ناحق بہتان باندھو گے اور کسی بھی اچھی بات میں ( اللہ کی ) نافرمانی نہ کرو گے۔ جو کوئی تم میں ( اس عہد کو ) پورا کرے گا تو اس کا ثواب اللہ کے ذمے ہے اور جو کوئی ان ( بری باتوں ) میں سے کسی کا ارتکاب کرے اور اسے دنیا میں ( اسلامی قانون کے تحت ) سزا دے دی گئی تو یہ سزا اس کے ( گناہوں کے ) لیے بدلا ہو جائے گی اور جو کوئی ان میں سے کسی بات میں مبتلا ہو گیا اور اللہ نے اس کے ( گناہ ) کو چھپا لیا تو پھر اس کا ( معاملہ ) اللہ کے حوالہ ہے، اگر چاہے معاف کرے اور اگر چاہے سزا دیدے۔ ( عبادہ کہتے ہیں کہ ) پھر ہم سب نے ان ( سب باتوں ) پر آپ صلی اللہ علیہ وسلم سے بیعت کر لی۔ ',
  'ہم سے (اس حدیث کو) عبداللہ بن مسلمہ نے بیان کیا، انہوں نے اسے مالک رحمہ اللہ سے نقل کیا، انہوں نے عبدالرحمٰن بن عبداللہ بن ابی صعصعہ سے، انہوں نے اپنے باپ (عبداللہ رحمہ اللہ) سے، وہ ابو سعید خدری سے نقل کرتے ہیں کہ   رسول اللہ صلی اللہ علیہ وسلم نے فرمایا وہ وقت قریب ہے جب مسلمان کا ( سب سے ) عمدہ مال ( اس کی بکریاں ہوں گی ) ۔ جن کے پیچھے وہ پہاڑوں کی چوٹیوں اور برساتی وادیوں میں اپنے دین کو بچانے کے لیے بھاگ جائے گا۔ ',
  'یہ حدیث ہم سے محمد بن سلام نے بیان کی، وہ کہتے ہیں کہ انہیں اس کی عبدہ نے خبر دی، وہ ہشام سے نقل کرتے ہیں، ہشام عائشہ رضی اللہ عنہا سے وہ فرماتی ہیں کہ   رسول اللہ صلی اللہ علیہ وسلم لوگوں کو کسی کام کا حکم دیتے تو وہ ایسا ہی کام ہوتا جس کے کرنے کی لوگوں میں طاقت ہوتی ( اس پر ) صحابہ رضی اللہ عنہم نے عرض کیا کہ یا رسول اللہ! ہم لوگ تو آپ جیسے نہیں ہیں ( آپ تو معصوم ہیں ) اور آپ کی اللہ پاک نے اگلی پچھلی سب لغزشیں معاف فرما دی ہیں۔ ( اس لیے ہمیں اپنے سے کچھ زیادہ عبادت کرنے کا حکم فرمائیے ) ( یہ سن کر ) آپ صلی اللہ علیہ وسلم ناراض ہوئے حتیٰ کہ خفگی آپ صلی اللہ علیہ وسلم کے چہرہ مبارک سے ظاہر ہونے لگی۔ پھر فرمایا کہ بیشک میں تم سب سے زیادہ اللہ سے ڈرتا ہوں اور تم سب سے زیادہ اسے جانتا ہوں۔ ( پس تم مجھ سے بڑھ کر عبادت نہیں کر سکتے ) ۔ ',
  'اس حدیث کو ہم سے سلیمان بن حرب نے بیان کیا، ان سے شعبہ نے، وہ قتادہ سے روایت کرتے ہیں، وہ انس رضی اللہ عنہ سے، اور وہ نبی کریم صلی اللہ علیہ وسلم سے نقل کرتے ہیں کہ   آپ صلی اللہ علیہ وسلم نے فرمایا، جس شخص میں یہ تین باتیں ہوں گی وہ ایمان کا مزہ پالے گا، ایک یہ کہ وہ شخص جسے اللہ اور اس کا رسول ان کے ماسوا سے زیادہ عزیز ہوں اور دوسرے یہ کہ جو کسی بندے سے محض اللہ ہی کے لیے محبت کرے اور تیسری بات یہ کہ جسے اللہ نے کفر سے نجات دی ہو، پھر دوبارہ کفر اختیار کرنے کو وہ ایسا برا سمجھے جیسا آگ میں گر جانے کو برا جانتا ہے۔ ',
  'کو حمیدی نے یہ حدیث بیان کی، انہوں نے کہا کہ ہم کو سفیان نے یہ حدیث بیان کی، وہ کہتے ہیں ہم کو یحییٰ بن سعید انصاری نے یہ حدیث بیان کی، انہوں نے کہا کہ مجھے یہ حدیث محمد بن ابراہیم تیمی سے حاصل ہوئی۔ انہوں نے اس حدیث کو علقمہ بن وقاص لیثی سے سنا، ان کا بیان ہے کہ میں نے مسجد نبوی میں منبر رسول صلی اللہ علیہ وسلم پر عمر بن خطاب رضی اللہ عنہ کی زبان سے سنا، وہ فرما رہے تھے کہ میں نے جناب رسول اللہ صلی اللہ علیہ وسلم سے سنا   آپ صلی اللہ علیہ وسلم فرما رہے تھے کہ تمام اعمال کا دارومدار نیت پر ہے اور ہر عمل کا نتیجہ ہر انسان کو اس کی نیت کے مطابق ہی ملے گا۔ پس جس کی ہجرت ( ترک وطن ) دولت دنیا حاصل کرنے کے لیے ہو یا کسی عورت سے شادی کی غرض ہو۔ پس اس کی ہجرت ان ہی چیزوں کے لیے ہو گی جن کے حاصل کرنے کی نیت سے اس نے ہجرت کی ہے۔ ',
  'ہم کو عبداللہ بن یوسف نے حدیث بیان کی، ان کو مالک نے ہشام بن عروہ کی روایت سے خبر دی، انہوں نے اپنے والد سے نقل کی، انہوں نے ام المؤمنین عائشہ صدیقہ رضی اللہ عنہا سے نقل کی آپ نے فرمایا کہ   ایک شخص حارث بن ہشام نامی نے نبی کریم صلی اللہ علیہ وسلم سے سوال کیا تھا کہ یا رسول اللہ! آپ پر وحی کیسے نازل ہوتی ہے؟ آپ صلی اللہ علیہ وسلم نے فرمایا کہ وحی نازل ہوتے وقت کبھی مجھ کو گھنٹی کی سی آواز محسوس ہوتی ہے اور وحی کی یہ کیفیت مجھ پر بہت شاق گذرتی ہے۔ جب یہ کیفیت ختم ہوتی ہے تو میرے دل و دماغ پر اس ( فرشتے ) کے ذریعہ نازل شدہ وحی محفوظ ہو جاتی ہے اور کسی وقت ایسا ہوتا ہے کہ فرشتہ بشکل انسان میرے پاس آتا ہے اور مجھ سے کلام کرتا ہے۔ پس میں اس کا کہا ہوا یاد رکھ لیتا ہوں۔ عائشہ رضی اللہ عنہا کا بیان ہے کہ میں نے سخت کڑاکے کی سردی میں نبی کریم صلی اللہ علیہ وسلم کو دیکھا ہے کہ آپ صلی اللہ علیہ وسلم پر وحی نازل ہوئی اور جب اس کا سلسلہ موقوف ہوا تو آپ صلی اللہ علیہ وسلم کی پیشانی پسینے سے شرابور تھی۔ ',
  'ہم کو یحییٰ بن بکیر نے یہ حدیث بیان کی، وہ کہتے ہیں کہ اس حدیث کی ہم کو لیث نے خبر دی، لیث عقیل سے روایت کرتے ہیں۔ عقیل ابن شہاب سے، وہ عروہ بن زبیر سے، وہ ام المؤمنین عائشہ رضی اللہ عنہا سے نقل کرتے ہیں کہ انہوں نے بتلایا کہ   نبی کریم صلی اللہ علیہ وسلم پر وحی کا ابتدائی دور اچھے سچے پاکیزہ خوابوں سے شروع ہوا۔ آپ صلی اللہ علیہ وسلم خواب میں جو کچھ دیکھتے وہ صبح کی روشنی کی طرح صحیح اور سچا ثابت ہوتا۔ پھر من جانب قدرت آپ صلی اللہ علیہ وسلم تنہائی پسند ہو گئے اور آپ صلی اللہ علیہ وسلم نے غار حرا میں خلوت نشینی اختیار فرمائی اور کئی کئی دن اور رات وہاں مسلسل عبادت اور یاد الٰہی و ذکر و فکر میں مشغول رہتے۔ جب تک گھر آنے کو دل نہ چاہتا توشہ ہمراہ لیے ہوئے وہاں رہتے۔ توشہ ختم ہونے پر ہی اہلیہ محترمہ خدیجہ رضی اللہ عنہا کے پاس تشریف لاتے اور کچھ توشہ ہمراہ لے کر پھر وہاں جا کر خلوت گزیں ہو جاتے، یہی طریقہ جاری رہا یہاں تک کہ آپ صلی اللہ علیہ وسلم پر حق منکشف ہو گیا اور آپ صلی اللہ علیہ وسلم غار حرا ہی میں قیام پذیر تھے کہ اچانک جبرائیل علیہ السلام آپ صلی اللہ علیہ وسلم کے پاس حاضر ہوئے اور کہنے لگے کہ اے محمد! پڑھو آپ صلی اللہ علیہ وسلم فرماتے ہیں کہ میں نے کہا کہ میں پڑھنا نہیں جانتا، آپ صلی اللہ علیہ وسلم فرماتے ہیں کہ فرشتے نے مجھے پکڑ کر اتنے زور سے بھینچا کہ میری طاقت جواب دے گئی، پھر مجھے چھوڑ کر کہا کہ پڑھو، میں نے پھر وہی جواب دیا کہ میں پڑھا ہوا نہیں ہوں۔ اس فرشتے نے مجھ کو نہایت ہی زور سے بھینچا کہ مجھ کو سخت تکلیف محسوس ہوئی، پھر اس نے کہا کہ پڑھ! میں نے کہا کہ میں پڑھا ہوا نہیں ہوں۔ فرشتے نے تیسری بار مجھ کو پکڑا اور تیسری مرتبہ پھر مجھ کو بھینچا پھر مجھے چھوڑ دیا اور کہنے لگا کہ پڑھو اپنے رب کے نام کی مدد سے جس نے پیدا کیا اور انسان کو خون کی پھٹکی سے بنایا، پڑھو اور آپ کا رب بہت ہی مہربانیاں کرنے والا ہے۔ پس یہی آیتیں آپ صلی اللہ علیہ وسلم جبرائیل علیہ السلام سے سن کر اس حال میں غار حرا سے واپس ہوئے کہ آپ صلی اللہ علیہ وسلم کا دل اس انوکھے واقعہ سے کانپ رہا تھا۔ آپ صلی اللہ علیہ وسلم خدیجہ کے ہاں تشریف لائے اور فرمایا کہ مجھے کمبل اڑھا دو، مجھے کمبل اڑھا دو۔ لوگوں نے آپ صلی اللہ علیہ وسلم کو کمبل اڑھا دیا۔ جب آپ صلی اللہ علیہ وسلم کا ڈر جاتا رہا۔ تو آپ صلی اللہ علیہ وسلم نے اپنی زوجہ محترمہ خدیجہ رضی اللہ عنہا کو تفصیل کے ساتھ یہ واقعہ سنایا اور فرمانے لگے کہ مجھ کو اب اپنی جان کا خوف ہو گیا ہے۔ آپ صلی اللہ علیہ وسلم کی اہلیہ محترمہ خدیجہ رضی اللہ عنہا نے آپ صلی اللہ علیہ وسلم کی ڈھارس بندھائی اور کہا کہ آپ کا خیال صحیح نہیں ہے۔ اللہ کی قسم! آپ کو اللہ کبھی رسوا نہیں کرے گا، آپ تو اخلاق فاضلہ کے مالک ہیں، آپ تو کنبہ پرور ہیں، بے کسوں کا بوجھ اپنے سر پر رکھ لیتے ہیں، مفلسوں کے لیے آپ کماتے ہیں، مہمان نوازی میں آپ بےمثال ہیں اور مشکل وقت میں آپ امر حق کا ساتھ دیتے ہیں۔ ایسے اوصاف حسنہ والا انسان یوں بے وقت ذلت و خواری کی موت نہیں پا سکتا۔ پھر مزید تسلی کے لیے خدیجہ رضی اللہ عنہا آپ صلی اللہ علیہ وسلم کو ورقہ بن نوفل کے پاس لے گئیں، جو ان کے چچا زاد بھائی تھے اور زمانہ جاہلیت میں نصرانی مذہب اختیار کر چکے تھے اور عبرانی زبان کے کاتب تھے، چنانچہ انجیل کو بھی حسب منشائے خداوندی عبرانی زبان میں لکھا کرتے تھے۔ ( انجیل سریانی زبان میں نازل ہوئی تھی پھر اس کا ترجمہ عبرانی زبان میں ہوا۔ ورقہ اسی کو لکھتے تھے ) وہ بہت بوڑھے ہو گئے تھے یہاں تک کہ ان کی بینائی بھی رخصت ہو چکی تھی۔ خدیجہ رضی اللہ عنہا نے ان کے سامنے آپ صلی اللہ علیہ وسلم کے حالات بیان کیے اور کہا کہ اے چچا زاد بھائی! اپنے بھتیجے ( محمد صلی اللہ علیہ وسلم ) کی زبانی ذرا ان کی کیفیت سن لیجیئے وہ بولے کہ بھتیجے آپ نے جو کچھ دیکھا ہے، اس کی تفصیل سناؤ۔ چنانچہ آپ صلی اللہ علیہ وسلم نے از اول تا آخر پورا واقعہ سنایا، جسے سن کر ورقہ بے اختیار ہو کر بول اٹھے کہ یہ تو وہی ناموس ( معزز راز دان فرشتہ ) ہے جسے اللہ نے موسیٰ علیہ السلام پر وحی دے کر بھیجا تھا۔ کاش، میں آپ کے اس عہد نبوت کے شروع ہونے پر جوان عمر ہوتا۔ کاش میں اس وقت تک زندہ رہتا جب کہ آپ کی قوم آپ کو اس شہر سے نکال دے گی۔ رسول اللہ صلی اللہ علیہ وسلم نے یہ سن کر تعجب سے پوچھا کہ کیا وہ لوگ مجھ کو نکال دیں گے؟ ( حالانکہ میں تو ان میں صادق و امین و مقبول ہوں ) ورقہ بولا ہاں یہ سب کچھ سچ ہے۔ مگر جو شخص بھی آپ کی طرح امر حق لے کر آیا لوگ اس کے دشمن ہی ہو گئے ہیں۔ اگر مجھے آپ کی نبوت کا وہ زمانہ مل جائے تو میں آپ کی پوری پوری مدد کروں گا۔ مگر ورقہ کچھ دنوں کے بعد انتقال کر گئے۔ پھر کچھ عرصہ تک وحی کی آمد موقوف رہی۔ ',
  'ابن شہاب کہتے ہیں مجھ کو ابوسلمہ بن عبدالرحمٰن نے جابر بن عبداللہ انصاری رضی اللہ عنہما سے یہ روایت نقل کی کہ   آپ صلی اللہ علیہ وسلم نے وحی کے رک جانے کے زمانے کے حالات بیان فرماتے ہوئے کہا کہ ایک روز میں چلا جا رہا تھا کہ اچانک میں نے آسمان کی طرف ایک آواز سنی اور میں نے اپنا سر آسمان کی طرف اٹھایا کیا دیکھتا ہوں کہ وہی فرشتہ جو میرے پاس غار حرا میں آیا تھا وہ آسمان و زمین کے بیچ میں ایک کرسی پر بیٹھا ہوا ہے۔ میں اس سے ڈر گیا اور گھر آنے پر میں نے پھر کمبل اوڑھنے کی خواہش ظاہر کی۔ اس وقت اللہ پاک کی طرف سے یہ آیات نازل ہوئیں۔ اے لحاف اوڑھ کر لیٹنے والے! اٹھ کھڑا ہو اور لوگوں کو عذاب الٰہی سے ڈرا اور اپنے رب کی بڑائی بیان کر اور اپنے کپڑوں کو پاک صاف رکھ اور گندگی سے دور رہ۔ اس کے بعد وحی تیزی کے ساتھ پے در پے آنے لگی۔ اس حدیث کو یحییٰ بن بکیر کے علاوہ لیث بن سعد سے عبداللہ بن یوسف اور ابوصالح نے بھی روایت کیا ہے۔ اور عقیل کے علاوہ زہری سے ہلال بن رواد نے بھی روایت کیا ہے۔ یونس اور معمر نے اپنی روایت میں لفظ «فواده» کی جگہ «بوادره» نقل کیا ہے۔ ',
  'موسیٰ بن اسماعیل نے ہم سے حدیث بیان کی، ان کو ابوعوانہ نے خبر دی، ان سے موسیٰ ابن ابی عائشہ نے بیان کی، ان سے سعید بن جبیر نے   انہوں نے ابن عباس رضی اللہ عنہما سے کلام الٰہی «لا تحرك به لسانك لتعجل به‏» الخ کی تفسیر کے سلسلہ میں سنا کہ رسول اللہ صلی اللہ علیہ وسلم نزول قرآن کے وقت بہت سختی محسوس فرمایا کرتے تھے اور اس کی ( علامتوں ) میں سے ایک یہ تھی کہ یاد کرنے کے لیے آپ اپنے ہونٹوں کو ہلاتے تھے۔ ابن عباس رضی اللہ عنہما نے کہا میں اپنے ہونٹ ہلاتا ہوں جس طرح آپ ہلاتے تھے۔ سعید کہتے ہیں میں بھی اپنے ہونٹ ہلاتا ہوں جس طرح ابن عباس رضی اللہ عنہما کو میں نے ہلاتے دیکھا۔ پھر انہوں نے اپنے ہونٹ ہلائے۔ ( ابن عباس رضی اللہ عنہما نے کہا ) پھر یہ آیت اتری کہ اے محمد! قرآن کو جلد جلد یاد کرنے کے لیے اپنی زبان نہ ہلاؤ۔ اس کا جمع کر دینا اور پڑھا دینا ہمارا ذمہ ہے۔ ابن عباس رضی اللہ عنہما کہتے ہیں یعنی قرآن آپ صلی اللہ علیہ وسلم کے دل میں جما دینا اور پڑھا دینا ہمارے ذمہ ہے۔ پھر جب ہم پڑھ چکیں تو اس پڑھے ہوئے کی اتباع کرو۔ ابن عباس رضی اللہ عنہما فرماتے ہیں ( اس کا مطلب یہ ہے ) کہ آپ اس کو خاموشی کے ساتھ سنتے رہو۔ اس کے بعد مطلب سمجھا دینا ہمارے ذمہ ہے۔ پھر یقیناً یہ ہماری ذمہ داری ہے کہ آپ اس کو پڑھو ( یعنی اس کو محفوظ کر سکو ) چنانچہ اس کے بعد جب آپ کے پاس جبرائیل علیہ السلام ( وحی لے کر ) آتے تو آپ ( توجہ سے ) سنتے۔ جب وہ چلے جاتے تو رسول اللہ صلی اللہ علیہ وسلم اس ( وحی ) کو اسی طرح پڑھتے جس طرح جبرائیل علیہ السلام نے اسے پڑھا تھا۔ ',
  'ہم کو عبدان نے حدیث بیان کی، انہیں عبداللہ بن مبارک نے خبر دی، ان کو یونس نے، انہوں نے زہری سے یہ حدیث سنی۔ (دوسری سند یہ ہے کہ) ہم سے بشر بن محمد نے یہ حدیث بیان کی۔ ان سے عبداللہ بن مبارک نے، ان سے یونس اور معمر دونوں نے، ان دونوں نے زہری سے روایت کی پہلی سند کے مطابق زہری سے عبیداللہ بن عبداللہ نے، انہوں نے ابن عباس رضی اللہ عنہما سے یہ روایت نقل کی کہ   رسول اللہ صلی اللہ علیہ وسلم سب لوگوں سے زیادہ جواد ( سخی ) تھے اور رمضان میں ( دوسرے اوقات کے مقابلہ میں جب ) جبرائیل علیہ السلام آپ صلی اللہ علیہ وسلم سے ملتے بہت ہی زیادہ جود و کرم فرماتے۔ جبرائیل علیہ السلام رمضان کی ہر رات میں آپ صلی اللہ علیہ وسلم سے ملاقات کرتے اور آپ صلی اللہ علیہ وسلم کے ساتھ قرآن کا دورہ کرتے، غرض نبی کریم صلی اللہ علیہ وسلم لوگوں کو بھلائی پہنچانے میں بارش لانے والی ہوا سے بھی زیادہ جود و کرم فرمایا کرتے تھے۔ ',
  'ہم سے عبیداللہ بن موسیٰ نے یہ حدیث بیان کی۔ انہوں نے کہا کہ ہمیں اس کی بابت حنظلہ بن ابی سفیان نے خبر دی۔ انہوں نے عکرمہ بن خالد سے روایت کی انہوں نے عبداللہ بن عمر رضی اللہ عنہما سے روایت کی کہ   رسول اللہ صلی اللہ علیہ وسلم نے فرمایا اسلام کی بنیاد پانچ چیزوں پر قائم کی گئی ہے۔ اول گواہی دینا کہ اللہ کے سوا کوئی معبود نہیں اور بیشک محمد صلی اللہ علیہ وسلم اللہ کے سچے رسول ہیں اور نماز قائم کرنا اور زکوٰۃ ادا کرنا اور حج کرنا اور رمضان کے روزے رکھنا۔ ',
  'ہم سے محمد بن سنان نے بیان کیا، کہا ہم سے فلیح نے بیان کیا (دوسری سند) اور مجھ سے ابراہیم بن المنذر نے بیان کیا، کہا مجھ سے میرے باپ (فلیح) نے بیان کیا، کہا ہلال بن علی نے، انہوں نے عطاء بن یسار سے نقل کیا، انہوں نے ابوہریرہ رضی اللہ عنہ سے کہ   ایک بار نبی کریم صلی اللہ علیہ وسلم لوگوں میں بیٹھے ہوئے ان سے باتیں کر رہے تھے۔ اتنے میں ایک دیہاتی آپ کے پاس آیا اور پوچھنے لگا کہ قیامت کب آئے گی؟ آپ صلی اللہ علیہ وسلم اپنی گفتگو میں مصروف رہے۔ بعض لوگ ( جو مجلس میں تھے ) کہنے لگے آپ صلی اللہ علیہ وسلم نے دیہاتی کی بات سنی لیکن پسند نہیں کی اور بعض کہنے لگے کہ نہیں بلکہ آپ نے اس کی بات سنی ہی نہیں۔ جب آپ صلی اللہ علیہ وسلم اپنی باتیں پوری کر چکے تو میں سمجھتا ہوں کہ آپ صلی اللہ علیہ وسلم نے یوں فرمایا وہ قیامت کے بارے میں پوچھنے والا کہاں گیا اس ( دیہاتی ) نے کہا ( یا رسول اللہ! ) میں موجود ہوں۔ آپ صلی اللہ علیہ وسلم نے فرمایا کہ جب امانت ( ایمانداری دنیا سے ) اٹھ جائے تو قیامت قائم ہونے کا انتظار کر۔ اس نے کہا ایمانداری اٹھنے کا کیا مطلب ہے؟ آپ صلی اللہ علیہ وسلم نے فرمایا کہ جب ( حکومت کے کاروبار ) نالائق لوگوں کو سونپ دئیے جائیں تو قیامت کا انتظار کر۔ ',
  'ہم سے ابوالنعمان نے بیان کیا، کہا ہم سے ابوعوانہ نے ابوبشر سے بیان کیا، انہوں نے یوسف بن ماہک سے، انہوں نے عبداللہ بن عمرو سے، انہوں نے کہا   ایک سفر میں جو ہم نے کیا تھا نبی کریم صلی اللہ علیہ وسلم ہم سے پیچھے رہ گئے اور آپ صلی اللہ علیہ وسلم ہم سے اس وقت ملے جب ( عصر کی ) نماز کا وقت آن پہنچا تھا ہم ( جلدی جلدی ) وضو کر رہے تھے۔ پس پاؤں کو خوب دھونے کے بدل ہم یوں ہی سا دھو رہے تھے۔ ( یہ حال دیکھ کر ) آپ صلی اللہ علیہ وسلم نے بلند آواز سے پکارا دیکھو ایڑیوں کی خرابی دوزخ سے ہونے والی ہے دو یا تین بار آپ صلی اللہ علیہ وسلم نے ( یوں ہی بلند آواز سے ) فرمایا۔ ',
];

List hadithE_bhukari = [
  'Narrated Anas: The Prophet said, Whoever possesses the following three qualities will have the sweetness (delight) of faith: 1. The one to whom Allah and His Apostle becomes dearer than anything else. 2. Who loves a person and he loves him only for Allah\'s sake. 3. Who hates to revert to Atheism (disbelief) as he hates to be thrown into the fire. ',
  'Narrated Anas: The Prophet said, Love for the Ansar is a sign of faith and hatred for the Ansar is a sign of hypocrisy. ',
  'Narrated \'Ubada bin As-Samit: who took part in the battle of Badr and was a Naqib (a person heading a group of six persons), on the night of Al-\'Aqaba pledge: Allah\'s Apostle said while a group of his companions were around him, Swear allegiance to me for: 1. Not to join anything in worship along with Allah. 2. Not to steal. 3. Not to commit illegal sexual intercourse. 4. Not to kill your children. 5. Not to accuse an innocent person (to spread such an accusation among people). 6. Not to be disobedient (when ordered) to do good deed. The Prophet added: Whoever among you fulfills his pledge will be rewarded by Allah. And whoever indulges in any one of them (except the ascription of partners to Allah) and gets the punishment in this world, that punishment will be an expiation for that sin. And if one indulges in any of them, and Allah conceals his sin, it is up to Him to forgive or punish him (in the Hereafter). \'Ubada bin As-Samit added: So we swore allegiance for these. (points to Allah\'s Apostle)',
  'Narrated Abu Said Al-Khudri: Allah\'s Apostle said, A time will come that the best property of a Muslim will be sheep which he will take on the top of mountains and the places of rainfall (valleys) so as to flee with his religion from afflictions.',
  'Narrated \'Aisha: Whenever Allah\'s Apostle ordered the Muslims to do something, he used to order them deeds which were easy for them to do, (according to their strength and endurance). They said, O Allah\'s Apostle! We are not like you. Allah has forgiven your past and future sins. So Allah\'s Apostle became angry and it was apparent on his face. He said, I am the most Allah fearing, and know Allah better than all of you do. ',
  'Narrated Anas: The Prophet said, Whoever possesses the following three qualities will taste the sweetness of faith: 1. The one to whom Allah and His Apostle become dearer than anything else. 2. Who loves a person and he loves him only for Allah\'s sake. 3. Who hates to revert to disbelief (Atheism) after Allah has brought (saved) him out from it, as he hates to be thrown in fire. ',
  'Narrated \'Umar bin Al-Khattab: I heard Allah\'s Apostle saying, The reward of deeds depends upon the intentions and every person will get the reward according to what he has intended. So whoever emigrated for worldly benefits or for a woman to marry, his emigration was for what he emigrated for. ',
  'Narrated \'Aisha: (the mother of the faithful believers) Al-Harith bin Hisham asked Allah\'s Apostle O Allah\'s Apostle! How is the Divine Inspiration revealed to you? Allah\'s Apostle replied, Sometimes it is (revealed) like the ringing of a bell, this form of Inspiration is the hardest of all and then this state passes off after I have grasped what is inspired. Sometimes the Angel comes in the form of a man and talks to me and I grasp whatever he says. \'Aisha added: Verily I saw the Prophet being inspired divinely on a very cold day and noticed the sweat dropping from his forehead (as the Inspiration was over). ',
  'Narrated \'Aisha: (the mother of the faithful believers) The commencement of the Divine Inspiration to Allah\'s Apostle was in the form of good dreams which came true like bright daylight, and then the love of seclusion was bestowed upon him. He used to go in seclusion in the cave of Hira where he used to worship (Allah alone) continuously for many days before his desire to see his family. He used to take with him the journey food for the stay and then come back to (his wife) Khadija to take his food likewise again till suddenly the Truth descended upon him while he was in the cave of Hira. The angel came to him and asked him to read. The Prophet replied, I do not know how to read. The Prophet added, The angel caught me (forcefully) and pressed me so hard that I could not bear it any more. He then released me and again asked me to read and I replied, \'I do not know how to read.\' Thereupon he caught me again and pressed me a second time till I could not bear it any more. He then released me and again asked me to read but again I replied, \'I do not know how to read (or what shall I read)?\' Thereupon he caught me for the third time and pressed me, and then released me and said, \'Read in the name of your Lord, who has created (all that exists), created man from a clot. Read! And your Lord is the Most Generous. (96.1, 96.2, 96.3) Then Allah\'s Apostle returned with the Inspiration and with his heart beating severely. Then he went to Khadija bint Khuwailid and said, Cover me! Cover me! They covered him till his fear was over and after that he told her everything that had happened and said, I fear that something may happen to me. Khadija replied, Never! By Allah, Allah will never disgrace you. You keep good relations with your kith and kin, help the poor and the destitute, serve your guests generously and assist the deserving calamity-afflicted ones. Khadija then accompanied him to her cousin Waraqa bin Naufal bin Asad bin \'Abdul \'Uzza, who, during the pre-Islamic Period became a Christian and used to write the writing with Hebrew letters. He would write from the Gospel in Hebrew as much as Allah wished him to write. He was an old man and had lost his eyesight. Khadija said to Waraqa, Listen to the story of your nephew, O my cousin! Waraqa asked, O my nephew! What have you seen? Allah\'s Apostle described whatever he had seen. Waraqa said, This is the same one who keeps the secrets (angel Gabriel) whom Allah had sent to Moses. I wish I were young and could live up to the time when your people would turn you out. Allah\'s Apostle asked, Will they drive me out? Waraqa replied in the affirmative and said, Anyone (man) who came with something similar to what you have brought was treated with hostility; and if I should remain alive till the day when you will be turned out then I would support you strongly. But after a few days Waraqa died and the Divine Inspiration was also paused for a while. ',
  'Narrated Jabir bin \'Abdullah Al-Ansari while talking about the period of pause in revelation reporting the speech of the Prophet While I was walking, all of a sudden I heard a voice from the sky. I looked up and saw the same angel who had visited me at the cave of Hira\' sitting on a chair between the sky and the earth. I got afraid of him and came back home and said, \'Wrap me (in blankets).\' And then Allah revealed the following Holy Verses (of Quran): \'O you (i.e. Muhammad)! wrapped up in garments!\' Arise and warn (the people against Allah\'s Punishment),... up to \'and desert the idols.\' (74.1-5) After this the revelation started coming strongly, frequently and regularly. ',
  'Narrated Said bin Jubair: Ibn \'Abbas in the explanation of the statement of Allah Move not your tongue concerning (the Quran) to make haste therewith. (75.16) said Allah\'s Apostle used to bear the revelation with great trouble and used to move his lips (quickly) with the Inspiration. Ibn \'Abbas moved his lips saying, I am moving my lips in front of you as Allah\'s Apostle used to move his. Said moved his lips saying: I am moving my lips, as I saw Ibn \'Abbas moving his. Ibn \'Abbas added, So Allah revealed \'Move not your tongue concerning (the Qur\'an) to make haste therewith. It is for Us to collect it and to give you (O Muhammad) the ability to recite it (the Quran)\' (75.16-17) which means that Allah will make him (the Prophet) remember the portion of the Qur\'an which was revealed at that time by heart and recite it. The statement of Allah: \'And when we have recited it to you (O Muhammad through Gabriel) then you follow its (Quran) recital\' (75.18) means \'listen to it and be silent.\' Then it is for Us (Allah) to make it clear to you\' (75.19) means \'Then it is (for Allah) to make you recite it (and its meaning will be clear by itself through your tongue). Afterwards, Allah\'s Apostle used to listen to Gabriel whenever he came and after his departure he used to recite it as Gabriel had recited it. ',
  'Narrated Ibn \'Abbas: Allah\'s Apostle was the most generous of all the people, and he used to reach the peak in generosity in the month of Ramadan when Gabriel met him. Gabriel used to meet him every night of Ramadan to teach him the Qur\'an. Allah\'s Apostle was the most generous person, even more generous than the strong uncontrollable wind (in readiness and haste to do charitable deeds). ',
  'Narrated Ibn \'Umar: Allah\'s Apostle said: Islam is based on (the following) five (principles): 1. To testify that none has the right to be worshipped but Allah and Muhammad is Allah\'s Apostle. 2. To offer the (compulsory congregational) prayers dutifully and perfectly. 3. To pay Zakat (i.e. obligatory charity) . 4. To perform Hajj. (i.e. Pilgrimage to Mecca) 5. To observe fast during the month of Ramadan. ',
  'Narrated Abu Huraira: While the Prophet was saying something in a gathering, a Bedouin came and asked him, When would the Hour (Doomsday) take place? Allah\'s Apostle continued his talk, so some people said that Allah\'s Apostle had heard the question, but did not like what that Bedouin had asked. Some of them said that Allah\'s Apostle had not heard it. When the Prophet finished his speech, he said, Where is the questioner, who inquired about the Hour (Doomsday)? The Bedouin said, I am here, O Allah\'s Apostle . Then the Prophet said, When honesty is lost, then wait for the Hour (Doomsday). The Bedouin said, How will that be lost? The Prophet said, When the power or authority comes in the hands of unfit persons, then wait for the Hour (Doomsday.) ',
  'Narrated `Abdullah bin `Amr: Once the Prophet remained behind us in a journey. He joined us while we were performing ablution for the prayer which was over-due. We were just passing wet hands over our feet (and not washing them properly) so the Prophet addressed us in a loud voice and said twice or thrice: Save your heels from the fire. ',
];

List hadith_muslim = [
  '  کہمس کے بجائے مطر وراق نےعبد اللہ بن بریدہ سے ، انہوں نے یحیی بن یعمر سے نقل کیا کہ جب معبد ( جہنی ) نے تقدیر کے بارے میں وہ ( سب ) کہا جو کہا ، تو ہم نے اسے سخت ناپسند کیا ( یحییٰ نے کہا ) میں اور حمید بن عبد الرحمٰن حمیری نے حج کیا .... اس کے بعد انہوں نے کہمس کے واسطے سے بیان کردہ حدیث کے مطابق حدیث بیان کی ، البتہ الفاظ میں کچھ کمی بیشی ہے',
  '  ( عبد اللہ بن بریدہ کے ایک تیسرے شاگرد ) عثمان بن غیاث نے یحییٰ بن یعمر اور حمید بن عبد الرحمٰن دونوں سے روایت کی ، دونوں نےکہا : ہم عبد اللہ بن عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے ملے اور ہم سے تقدیر کی بات کی اور وہ لوگ ( منکرین تقدیر ) جو کچھ کہتے ہیں ، اس کا ذکر کیا ۔ اس کے بعد ( عثمان بن غیاث نے ) سابقہ راویوں کے مطابق حضرت عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے مرفوعاً روایت کی ۔ اس روایت میں کچھ الفاظ زیادہ ہیں اور کچھ انہوں نے کم کیے ہیں ۔ ',
  '  معتمر کے والد ( سلیمان بن طرخان ) نے یحییٰ بن یعمر سے ، انہوں نے عبد اللہ بن عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے ، انہوں نے حضرت عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے اور انہوں نے نبی ﷺ سے اسی طرح روایت کی جس طرح مذکورہ اساتذہ نے روایت کی ۔ ',
  '  ( ابن علیہ کے بجائے ) محمد بن بشر نےکہا : ہمیں ابو حیان نے سابقہ سند سے وہی حدیث بیان کی ، البتہ ان کی روایت میں : إذا ولدت الأمة بعلها ’’ جب لونڈی اپنا مالک جنے گی ‘ ‘ ( رب کی جگہ بعل ، یعنی مالک ) کے الفاظ ہیں ۔ ( أمة سے مملوکہ ) لونڈیاں مراد ہیں ۔ ',
  '  مالک بن انس نے ابو سہیل سے ، اور انہوں نے اپنے والد سے روایت کی ، انہوں نے حضرت طلحہ بن عبیداللہ ‌رضی ‌اللہ ‌عنہ ‌ ‌ سےسنا ، وہ کہہ رہے تھے کہ رسول اللہ ﷺ کے پاس اہل نجد میں سے ایک آدمی آیا ، اس کے بال پراگندہ تھے ، ہم اس کی ہلکی سی آواز سن رہے تھے لیکن جوکچھ وہ کہہ رہا تھا ہم اس کو سمجھ نہیں رہے تھے حتی کہ وہ رسو ل اللہ ﷺ کے قریب آ گیا ، وہ آپ سے اسلام کے بارے میں پوچھ رہا تھا ، رسول اللہ ﷺ نے فرمایا : ’’دن اور رات میں پانچ نمازیں ( فرض ) ہیں ۔ ‘ ‘ اس نے پوچھا : کیا ان کے علاوہ ( اور نمازیں ) بھی میرے ذمے ہیں ؟ آپ نے فرمایا : ’’نہیں : الا یہ کہ تم نفلی نماز پڑھو اور ماہ رمضان کے روزے ہیں ۔ ‘ ‘ اس نے پوچھا : کیا میرے ذمے اس کے علاوہ بھی ( روزے ) ہیں ؟ فرمایا : ’’نہیں ، الا یہ کہ تم نفلی روزے رکھو ۔ ‘ ‘ پھر رسول اللہ ﷺ اسے زکاۃ کے بارے میں بتایا تو اس نے سوال کیا : کیا میرے ذمے اس کےسوا بھی کچھ ہے ؟ آپ نے جواب دیا : ’’نہیں ، سوائے اس کے کہ تم اپنی مرضی سے ( نفلی صدقہ ) دو ۔ ‘ ‘ ( حضرت طلحہ نے ) کہا : پھر وہ آدمی واپس ہوا تو کہہ رہا تھا : اللہ کی قسم ! میں نے اس پر کوئی اضافہ کروں گا نہ اس میں کوئی کمی کروں گا ۔ اس پر رسول اللہ ﷺ نے فرمایا : ’’یہ فلاح پا گیا اگر اس نے سچ کر دکھایا ۔ ‘ ‘ ',
  '  اسماعیل بن جعفر نے ابو سہیل سے ، انہوں نے اپنے والد سے ، انہوں نےحضرت طلحہ بن عبید اللہ ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے اور انہوں نے نبی ﷺ سے ، مالک سے حدیث کی طرح روایت کی ، سوائے اس کے کہ کہا : رسول اللہ ﷺ نے فرمایا : ’’کامیاب ہوا ، اس کے باپ کی قسم ! اگر اس نے سچ کر دکھایا ِ ‘ ‘ یا ( فرمایا : ) ’’جنت میں داخل ہو گا ، اس کے باپ کی قسم ! اگر اس نے سچ کر دکھایا ۔ ‘ ‘ ',
  '  بہزنے کہا : ہمیں سلیمان بن مغیرہ نے ثابت سے حدیث سنائی اور انہوں نے حضرت انس ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے روایت کی ، انہون نےکہا : ہمیں قرآن مجید میں اس بات سے منع کر دیا گیا کہ ( بلاضرورت ) کسی چیز کے بارے میں آپ سے سوال کریں .... اس کے بعد ( بہزنے ) اسی کی مانند حدیث بیان کی ۔ ',
  '  عمر و بن عثمان نے کہا : ہمیں موسیٰ بن طلحہ نےحدیث سنائی ، انہوں نےکہا : مجھےحضرت ابوایوب ‌رضی ‌اللہ ‌عنہ ‌ ‌ نےحدیث سنائی کہ رسول ا للہ ﷺ ایک سفر میں تھے جب ایک اعرابی ( دیہاتی ) آپ کے سامنے آ کھڑا ہوا ، اس نے آپ کی اونٹنی کی مہار یانکیل پکڑ لی ، پھر کہا : اے اللہ کے رسول ! ( یا اے محمد! ) مجھے وہ بات بتائیے جو مجھے جنت کے قریب اور آگ سے دور کر دے ۔ ابو ایوب نے کہا کہ رسول اللہ ﷺ رک گئے ، پھر اپنے ساتھیوں پر نظر دوڑائی ، پھر فرمایا ، ’’اس کو توفیق ملی ) ( یا ہدایت ملی ) ‘ ‘ پھر بدوی نے پوچھا : ’’تم نے کیا بات کی ؟ ‘ ‘ اس نے اپنی بات دہرائی تو نبی ا کرمﷺ نے فرمایا : ’’تم اللہ تعالیٰ کی بندگی کرو ، اس کے ساتھ کسی کو شریک نہ ٹھہراؤ ، نماز قائم کرو ، زکاۃ ادا کرو اورصلہ رحمی کرو ۔ ( اب ) اونٹنی کو چھوڑ دو ۔ ‘ ‘ ',
  '  محمد بن عثمان بن عبد اللہ بن موہب اور ان کے والد عثمان دونوں موسیٰ بن طلحہ سے سنا وہ حضرت ابو ایوب ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے اور وہ نبی کریم ﷺ سے سابقہ حدیث کی مانند بیان کرتے تھے ۔ ',
  '  یحییٰ بن یحییٰ تمیمی او رابوبکر بن ابی شیبہ نے کہا : ہمیں ابو احوص نے حدیث بیان کی ، انہوں نے ابو اسحاق سے ، انہوں نے موسیٰ بن طلحہ سے او رانہوں حضرت ابو ایوب ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے روایت کی ، انہوں نے کہا : ایک آدمی نبی ﷺ کےپاس آیا اور پوچھا : مجھے کوئی ایسا کام بتائیے جس پر میں عمل کروں تو وہ مجھے جنت کے قریب اور آگ سے دور کر دے ۔ آپ نے فرمایا : ’’ یہ کہ تو اللہ کی بندگی کرے اس کے ساتھ کسی کو شریک نہ ٹھہرائے ، نماز کی پابندی کرے ، زکاۃ ادا کرے اور اپنے رشتہ داروں سے صلہ رحمی کرے ۔ ‘ ‘ جب وہ پیٹھ پھیر کر چل دیا تو رسول اللہ ﷺ نے فرمایا : ’’ اگر اس نے ان چیزوں کی پابندی کی جن کا اسے حکم دیا گیا ہے تو جنت میں داخل ہو گا ۔ ‘ ‘ ابن ابی شیبہ کی روایت میں ہے ، ’’اگر اس نے اس کی پابندی کی ( تو جنت میں داخل ہو گا ۔ ) ‘ ‘ ',
  '  حضرت ابو ہریرہ ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے روایت ہے کہ ایک اعرابی رسول اللہ ﷺ کے پاس آیا اور کہا : اے اللہ کے رسول ! مجھے ایسا عمل بتائیے کہ جب میں اس پر عمل کروں تو جنت میں داخل ہو جاؤں ۔ آپ نے فرمایا : ’’تم اللہ کی بندگی کرو اس کے ساتھ کسی کو شریک نہ ٹھہراؤ ، نماز قائم کرو جو تم پر لکھ دی گئی ہے ، فرض زکاۃ ادا کرو او ررمضان کے روزے رکھو ۔ ‘ ‘ وہ کہنے لکا : اس ذات کی قسم جس کے ہاتھ میں میری جان ہے ! میں نہ کبھی اس پر کسی چیز کا اضافہ کروں گا اور نہ اس میں گمی کروں گا ۔ جب وہ واپس جانے لگا تو نبی اکریم ﷺ نے فرمایا : ’’جسے اس بات سے خوشی ہو کہ وہ ایک جنتی آدمی دیکھے تو وہ اسے دیکھ لے ۔ ‘ ‘ ',
  '  ابومعاویہ نے اعمش سے حدیث سنائی ، انہوں نے ابو سفیان سے اور انہوں نے حضرت جابر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے روایت کی کہ رسول اللہ ﷺ کے پاس نعمان بن قوقل ‌رضی ‌اللہ ‌عنہ ‌ ‌ آئے اور کہا : اے اللہ کے رسول ! آپ کیا فرماتے ہیں کہ جب میں فرض نماز ادا کروں ، حرام کو حرام اور حلال کو حلال سمجھوں تو کیا میں جنت میں داخل ہو جاؤں گا ؟ نبی ﷺ نے فرمایا : ’’ہاں! ‘ ‘ ',
  '  شیبان نے اعمش سے ، انہوں نے ابو صالح اور ابو سفیان سے اور انہوں نے حضرت جابر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے روایت کی ، انہوں نے کہا : نعمان بن قوقل ‌رضی ‌اللہ ‌عنہ ‌ ‌ نے عرض کی : اے اللہ کےرسول !..... پھر اس سابقہ روایت کی طرح ہے اور اس میں یہ اضافہ کیا : اور اس پر کسی چیز کا اضافہ نہ کروں گا ۔ ',
  ' سلمہ بن شبیب ‘ حسن بن اعین ‘ معقل یعنی عبد اللہ ‘ ابوالزبیر ‘ جابر سے روایت ہے کہ ایک شخص نے رسول اللہﷺکی خدمت میں حاضر ہو کر عرض کیا کہ اگر میں فرض نماز پڑھتا رہوں اور ‌رمضان ‌كے ‌روزے ‌ركھوں ‌اور حلال کو حلال سمجھوں ‌اور ‌حرام ‌كو ‌حرام ‌، ‌اس ‌سے ‌زیادہ ‌كچھ ‌نہ ‌كروں تو آپﷺ کی کیا رائے ہے کہ کیا میں جنت میں داخل ہو جاؤ نگا؟تو آپﷺ نے فرمایا ہاں!اس شخص نے عرض کیا اللہ کی قسم میں اس سے زیادہ کچھ نہیں کرونگا ۔',
  '  ابو خالد سلیمان بن حیان احمر نے ابومالک اشجعی سے ، انہوں نے سعد بن عبیدہ سے ، انہوں نے حضرت ابن عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ سے اور انہوں نے نبی اکرم ﷺ سے روایت کی ، آپ ﷺ نے فرمایا : ’’ اسلام کی بنیاد پانچ چیزوں پر رکھی گئی ہے : اللہ کو یکتا قرار دینے ، نمازقائم کرنے ، زکاۃ ادا کرنے ، رمضان کے روزے رکھنے اور حج کرنے پر ۔ ‘ ‘ ایک شخص نے کہ : حج کرنے اور رمضان کے روزے رکھنے پر ؟ ابن عمر ‌رضی ‌اللہ ‌عنہ ‌ ‌ نے کہا : نہیں ! رمضان کے روزے رکھنے اور حج کرنے پر ۔ میں نے رسول اللہ ﷺ سے یہ بات اسی طرح ( اسی ترتیب سے ) سنی تھی ۔ ',
];

List hadithE_muslim = [
  'It is narrated on the authority of Yahya b. Ya\'mur that when Ma\'bad discussed the problem pertaining to Divine Decree, we refuted that. He (the narrator) said:I and Humaid b. Abdur-Rahman Himyari argued. And they carried on the conversation about the purport of the hadith related by Kahmas and its chain of transmission too, and there is some variation of words. ',
  'It is narrated on the authority of Yahya b. Ya\'mur and Humaid b. \'Abdur-Rahman that they said:We met Abdullah b. \'Umar and we discussed about the Divine Decree, and what they talked about it and he narrated the hadith that has been transmitted by \'Umar (may Allah be pleased with him) from the Apostle ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ). There is a slight variation in that. ',
  'The same hadith is mentioned through a different chain. ',
  'This hadith is narrated to us on the authority of Muhammad b. \'Abdullah b. Numair, on the authority of Muhammad b. Bishr, on the authority of Abd Hayyan al-Taymi with the exception that in this narration (instead of the words (Iza Waladat al\'amah rabbaha), the words are (Iza Waladat al\'amah Ba\'laha), i, e, when slave-girl gives birth to her master. ',
  'It is reported on the authority of Talha b. \'Ubaidullah that a person with dishevelled hair, one of the people of Nejd, came to the Messenger of Allah ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ). We heard the humming of his voice but could not fully discern what he had been saying, till he came nigh to the Messenger of Allah ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ). It was then (disclosed to us) that he was asking questions pertaining to Islam. The Messenger of Allah ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) said:Five prayers during the day and the night. (Upon this he said: Am I obliged to say any other (prayer) besides these? He (the Holy Prophet, ) said: No, but whatever you observe voluntarily, out of your own free will, and the fasts of Ramadan. The inquirer said: Am I obliged to do anything else besides this? He (the Holy Prophet) said: No, but whatever you do out of your own free will. And the Messenger of Allah told him about the Zakat (poor-rate). The inquirer said: Am I obliged to pay anything else besides this? He (the Holy Prophet) said: No, but whatever you pay voluntarily out of your own free will. The man turned back and was saying: I would neither make any addition to this, nor will decrease anything out of it. The Prophet remarked: He is successful, if he is true to what he affirms. ',
  'Another hadith, the like of which has been narrated by Malik (b. Anas) (and mentioned above) is also reported by Talha b. \'Ubaidullah, with the only variation that the Prophet remarked:By his father, he shall succeed if he were true (to what he professed), or: By his father, he would enter heaven if he were true (to what he professed). ',
  'It is narrated on the authority of Thabit that Anas said:We were forbidden in the Holy Qur\'an that we should ask about anything from the Messenger of Allah ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) and then Anas reported the hadith in similar words. ',
  'It is narrated on the authority of Abu Ayyub Ansari that once during the journey of the Prophet (may peace of Allah be upon him) a bedouin appeared before him and caught hold of the nosestring of his she-camel and then said, Messenger of Allah (or Muhammad), inform me about that which takes me near to Paradise and draws me away from the Fire (of Hell). He (the narrator) said:The Prophet ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) stopped for a while and cast a glance upon his companions and then said: He was afforded a good opportunity (or he had been guided well). He (the Holy Prophet) addressing the bedouin said: (Repeat) whatever you have uttered. He (the bedouin) repeated that. Upon this the Apostle ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) remarked: The deed which can draw you near to Paradise and take you away from Hell is, that you worship Allah and associate none with Him, and you establish prayer and pay Zakat, and do good to your kin. After having uttered these words, the Prophet asked the bedouin to release the nosestring of his she-camel. ',
  'This hadith is transmitted by Muhammad b. Hatim on the authority of Abu Ayyub Ansari. ',
  'It is narrated on the authority of Abu Ayyub that a man came to the Prophet ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) and said:Direct me to a deed which draws me near to Paradise and takes me away from the Fire (of Hell). Upon this he (the Holy Prophet) said: You worship Allah and never associate anything with Him, establish prayer, and pay Zakat, and do good to your kin. When he turned his back, the Messenger of Allah ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) remarked: If he adheres to what he has been ordered to do, he would enter Paradise. ',
  'It is reported on the authority of Abu Huraira that a bedouin came to the Messenger of Allah ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) and said:Messenger of Allah, direct me to a deed by which I may be entitled to enter Paradise. Upon this he (the Holy Prophet) remarked: You worship Allah and never associate anything with Him, establish the obligatory prayer, and pay the Zakat which is incumbent upon you, and observe the fast of Ramadan. He (the bedouin) said: By Him in Whose hand is my life, I will never add anything to it, nor will I diminish anything from it. When he (the bedouin) turned his back, the Prophet ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) said: He who is pleased to see a man from the dwellers of Paradise should catch a glimpse of him. ',
  'It is narrated on the authority of Jabir that Nu\'man b. Qaufal came to the Prophet ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) and said:Would I enter Paradise if I say the obligatory prayers and deny myself that which is forbidden and treat that as lawful what has been made permissible (by the Shari\'ah)? The Prophet ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ) replied in the affirmative. ',
  'A similar hadith is narrated on Jabir\'s authority in which the following words are added:I will do nothing more. ',
  'It is narrated on the authority of Jabir that a man once said to the Messenger of Allah ( ‌صلی ‌اللہ ‌علیہ ‌وسلم ‌ ):Shall I enter Paradise in case I say the obligatory prayers, observe the (fasts) of Ramadan and treat that as lawful which has been made permissible (by the Shari\'ah) and deny myself that what is forbidden, and make no addition to it? He (the Holy Prophet) replied in the affirmative. He (the inquirer) said: By Allah, I would add nothing to it. ',
  'It is narrated on the authority of (\'Abdullah) son of Umar (may Allah be pleased with them) that the Prophet (may peace of Allah be upon him) said:(The superstructure of) al-Islam is raised on five (pillars), i. e. the oneness of Allah, the establishment of prayer, payment of Zakat, the, fast of Ramadan, Pilgrimage (to Mecca). A person said (to \'Abdullah b. Umar the narrator): Which of the two precedes the other-Pilgrimage or the fasts of Rarnadan? Upon this he (the narrator) replied: No (it is not the Pilgrimage first) but the fasts of Ramadan precede the Pilgrimage. ',
];

List kalma = [
  'لَا إِلَٰهَ إِلَّا ٱللَّٰهُ مُحَمَّدٌ رَسُولُ ٱللَّٰهِ',
  'أشْهَدُ أنْ لَا إِلَٰهَ إِلَّا ٱللَّٰهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ ٱللَّٰهِ',
  'سُبْحَانَ اللّٰہِ وَالْحَمْدُ لِلّٰہِ وَلَا اِلٰهَ اِلَّا اللّٰہُ وَاللّٰہُ اَکْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ اِلَّا بِاللّٰہِ الْعَلِیِّ الْعَظِیْمِ',
  'لَآ اِلٰهَ اِلَّا اللهُ وَحْدَهٗ لَا شَرِيْكَ لَهٗ لَهُ الْمُلْكُ وَ لَهُ الْحَمْدُ يُحْىٖ وَ يُمِيْتُ وَ هُوَحَیٌّ لَّا يَمُوْتُ اَبَدًا اَبَدًاؕ ذُو الْجَلَالِ وَالْاِكْرَامِؕ بِيَدِهِ الْخَيْرُؕ وَهُوَ عَلٰى كُلِّ شیْ ٍٔ قَدِیْرٌؕ',
  'اسْتَغْفِرُ اللّهَ رَبِّىْ مِنْ كُلِّ ذَنْبٍ اَذْنَبْتُه عَمَدًا اَوْ خَطَاً سِرًّا اَوْ عَلَانِيَةً وَاَتُوْبُ اِلَيْهِ مِنْ الذَّنْبِ الَّذِىْ اَعْلَمُ وَ مِنْ الذَّنْبِ الَّذِىْ لا اَعْلَمُ اِنَّكَ اَنْتَ عَلَّامُ الغُيُبِ وَ سَتَّارُ الْعُيُوْبِ و َغَفَّارُ الذُّنُوْبِ وَ لا حَوْلَ وَلا قُوَّةَ اِلَّا بِاللّهِ الْعَلِىِّ العَظِيْم’',
  'ٱللَّٰهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ أَنْ أُشْرِكَ بِكَ شَيْءً وَأَنَا أَعْلَمُ بِهِ وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ بِهِ تُبْتُ عَنْهُ وَتَبَرَّأَتُ مِنَ ٱلْكُفْر وَٱلشِّرْكِ وَٱلْكِذْبِ وَٱلْغِيبَةِ وَٱلْبِدْعَةِ وَٱلنَّمِيمَةِ وَٱلْفَوَاحِشِ وَٱلْبُهْتَانِ وَٱلْمَعَاصِي كُلِّهَا وَأَسْلَمْتُ وَأَقُولُ لَا إِلَٰهَ إِلَّا ٱللَّٰهُ مُحَمَّدٌ رَسُولُ ٱللَّٰهِ',
];

List kalmaE = [
  'اللہ کے سوا کوئی معبود نہیں، اور محمد ﷺ اللہ کے رسول ہیں۔',
  'میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں، اور میں گواہی دیتا ہوں کہ محمد ﷺ اللہ کے رسول ہیں۔',
  'اللہ تعالی کی تعریف اور عزت ہے، اللہ تعالی بزرگ ہے اور اللہ تعالی ہی سب سے بڑا ہے، اور کوئی قوت و قدرت اللہ تعالی کے بغیر نہیں۔',
  'اللہ تعالی کے سوا کوئی معبود نہیں، وہ اکیلا ہے اور کوئی شریک نہیں۔ سب حکومت اسی کی ہے اور تمام تعریفیں بھی اسی کے لئے ہیں۔ وہ زندگی دیتا ہے اور موت دیتا ہے، وہ زندہ ہے اور مرنے والا نہیں ہے۔ ہر نیکی اس کے ہاتھ میں ہے اور وہ ہر چیز پر قادر ہے',
  'اللہ سے میں معافی کی التجا کرتا ہوں، جو میرے رب ہیں۔ میں اپنے سب گناہوں کے لئے معافی چاہتا ہوں، اور جو گناہ میں نے اپنی مرضی سے یا غلطی سے کیا ہو، پوشیدہ یا ظاہر، ان سب کے لئے اپنی طرف سے توبہ کرتا ہوں۔ اور جن گناہوں کا میں علم رکھتا ہوں اور جن کے بارے میں مجھے علم نہیں، ان سب کے لئے بھی معافی کی التجا کرتا ہوں۔ بیشک تو پوشیدہ باتوں کا جاننے والا ہے، عیوب کو چھپانے والا ہے اور بخشنے والا ہے۔ اور گناہوں سے بچنے کی طاقت اور نیک کام کرنے کی طاقت اللہ ہی کی طرف سے ہے۔ جو عالی شان اور عظمت والا ہے',
  'آے اللہ میں پناہ مانگتا ہو اس بات سے کہ میں کسی شے کو تیرا شریک بناو جان بوجھ کر،اور بخشش مانگتاہو میں تم سے اس کام کی جو میں جانتا نہیں ہواور میں نے اس سے توبہ کیا اور بیزار ہوا کفر سے، شرک سے، اور جھوٹ سے، اور غیبت سے، اور بدعت سے ، اور چغلی سے ، اور بے حیائی سے، اور بہتان سے اور تمام گناہو سے اور میں اسلام لایا اور میں کہتا ہوکہ اللہ کے سوا کوئی معبود نہیں اور محمد ﷺ اللہ کے رسول ہے۔',
];
